name: Build KillrVideo Java backend
on:
    push:
      branches: [ "main" ]
    merge:
      branches: [ "main" ]
jobs:
  build:
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'semeru'
        java-version: '21'
    - name: Build with Maven
      run: mvn -B package --file pom.xml
